name: Deploy FastAPI to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies locally into site_packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t ./site_packages

      - name: Prepare ZIP package
        run: |
          mkdir package
          cp -r app package/
          cp -r migrations package/
          cp alembic.ini package/
          cp requirements.txt package/
          cp application.py package/
          cp DATOS.txt package/
          cp -r site_packages/* package/

          cd package
          zip -r ../app.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app.zip

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "MJSOSPHIA-API"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: "app.zip"
